# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/snorre-k/idrive-docker:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: IDrive"
  org.opencontainers.image.description: "Host IDrive as an Home Assistant Addon"
  org.opencontainers.image.source: "https://github.com/dmostert/hassio-idrive"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
